### ISSUE TITLE
Potentially Incorrect Formula for Wilkinson's Shift

### ISSUE THREAD

**Issue by willchet** [hbldh/b2ac#8]
In the `QR_algorithm_Wilkinson_shift` algorithm, the Wilkinson's shift is calculated in [this line](https://github.com/hbldh/b2ac/blob/77a13ab29ae44b32238e754bff1d2cc6e20883dd/b2ac/eigenmethods/qr_algorithm.py#L322). I believe this should instead be:
```
mu = T[m, m] - np.sign(delta) * T[m, m - 1]**2 / \
             (np.abs(delta) + np.linalg.norm([delta, T[m, m - 1]]))
```

Note that this is `T[m, m - 1]**2` instead of `T[m, m - 1]`. This is the formula given in sources such as [here](https://people.inf.ethz.ch/arbenz/ewp/Lnotes/2010/chapter3.pdf) and [here](https://dspace.mit.edu/bitstream/handle/1721.1/75282/18-335j-fall-2006/contents/lecture-notes/lec16.pdf).

Figured I would let you know in case this is a bug.

**Comment by hbldh** [comment]
I had to go back to my source, the notation of Golub and van Loan's [Matrix Computations](https://www.researchgate.net/profile/Vikash-Pandey-7/post/how_to_use_matrix_for_analysis/attachment/59d62ab379197b8077989148/AS%3A340211683872769%401458124195177/download/Golub_Matrix_Computations.pdf), page 462-463, but it does not look different from the sources you cite.

It does say this:
<img width="228" alt="image" src="https://github.com/user-attachments/assets/3983135f-80cc-44bd-acfb-a19e0c87384b">
and my code is very apparently wrong. 

I appreciate your scrutiny of my code; it was after all 11 years since I wrote it and it is fun to know that someone has at least had a glance at it closely enough to find this. Send a PR and I will merge it.
